#!/usr/bin/env python3
"""Vendor nayuki's QR-Code-generator (C) into src/BarcodeKit/qrcodegen.h.

BarcodeKit is header-only and targets AVR, so the upstream .c/.h pair is
folded into one header with a small, mechanical set of changes. Running this
script against a fresh checkout reproduces the vendored file exactly, which is
what makes updating to a new upstream commit a review of this script's output
rather than a manual merge.

Usage:
    git clone --depth 1 https://github.com/nayuki/QR-Code-generator.git /tmp/qrgen
    python tools/vendor_qrcodegen.py /tmp/qrgen

Changes applied (all mechanical, none touch the algorithm):

1. The .h and .c are concatenated into one header, with the upstream license
   notice kept verbatim at the top.
2. Everything is wrapped in `namespace BarcodeKit { namespace qrcodegen { ... } }`
   so the names cannot collide with a copy the user already has.
3. Every function becomes `inline` (header-only: one definition per program).
4. The two [4][41] error-correction tables get BARCODEKIT_TABLE / a read
   accessor, so they live in flash on AVR instead of eating 328 bytes of RAM.
5. assert() becomes a no-op on AVR and under NDEBUG: the __FILE__ strings cost
   real flash, and a failed assertion on a microcontroller would abort the
   sketch. Host builds keep the assertions, which is where the tests run.
6. <stdbool.h> is dropped (C++ has bool); the remaining C includes are hoisted
   to the top of the generated header.
"""

import re
import sys
from pathlib import Path

HEADER = """// BarcodeKit - vendored copy of nayuki's QR Code generator (C), folded into a
// single header.
//
//   Upstream: https://github.com/nayuki/QR-Code-generator
//   Commit:   {commit}
//   License:  MIT (reproduced below)
//
// Generated by tools/vendor_qrcodegen.py - do not edit by hand. See that
// script for the list of changes applied to the upstream source.

#pragma once

#include "Common.h"  // BARCODEKIT_TABLE / BARCODEKIT_READ8

#include <assert.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>  // abs, labs
#include <string.h>

// A failed assertion would abort the sketch, and the __FILE__ strings cost
// flash we do not have on AVR. Host builds - where the tests run - keep them.
#if defined(__AVR__) || defined(NDEBUG)
#undef assert
#define assert(cond) ((void)0)
#endif

namespace BarcodeKit {{
namespace qrcodegen {{

"""

FOOTER = """
}  // namespace qrcodegen
}  // namespace BarcodeKit
"""

# The two big tables: keep the data verbatim, read through BARCODEKIT_READ8.
TABLE_PATCH = [
    ("testable const int8_t ECC_CODEWORDS_PER_BLOCK[4][41] = {",
     "testable const int8_t ECC_CODEWORDS_PER_BLOCK[4][41] BARCODEKIT_TABLE = {"),
    ("testable const int8_t NUM_ERROR_CORRECTION_BLOCKS[4][41] = {",
     "testable const int8_t NUM_ERROR_CORRECTION_BLOCKS[4][41] BARCODEKIT_TABLE = {"),
    ("NUM_ERROR_CORRECTION_BLOCKS[(int)ecl][version]",
     "(int)BARCODEKIT_READ8(&NUM_ERROR_CORRECTION_BLOCKS[(int)ecl][version])"),
    ("ECC_CODEWORDS_PER_BLOCK  [(int)ecl][version]",
     "(int)BARCODEKIT_READ8(&ECC_CODEWORDS_PER_BLOCK[(int)ecl][version])"),
    ("- ECC_CODEWORDS_PER_BLOCK    [e][v]\n\t\t* NUM_ERROR_CORRECTION_BLOCKS[e][v];",
     "- (int)BARCODEKIT_READ8(&ECC_CODEWORDS_PER_BLOCK[e][v])\n"
     "\t\t* (int)BARCODEKIT_READ8(&NUM_ERROR_CORRECTION_BLOCKS[e][v]);"),
]

# int8_t read back through pgm_read_byte is unsigned; these tables hold -1 for
# the unused version 0, but every read is guarded by version >= 1, so the sign
# never matters. Cast to int keeps the arithmetic identical on both paths.

FUNC_START = re.compile(
    r"^(static |testable |)"
    r"((?:const )?(?:struct qrcodegen_Segment|enum qrcodegen_\w+|unsigned |long |"
    r"void|bool|int|uint8_t|int8_t|size_t|char|float)[\w \*]*)"
    r"(\w+\()"
)


def strip_guarded(text: str) -> str:
    """Drop the parts of the .h we replace: include guards and C includes."""
    text = text.replace("#pragma once\n", "")
    for inc in ("#include <stdbool.h>", "#include <stddef.h>", "#include <stdint.h>",
                "#include <assert.h>", "#include <limits.h>", "#include <stdlib.h>",
                "#include <string.h>", '#include "qrcodegen.h"'):
        text = text.replace(inc + "\n", "")
    return text


def inline_functions(text: str) -> str:
    """Mark every function definition inline (header-only)."""
    out = []
    for line in text.split("\n"):
        m = FUNC_START.match(line)
        if m and not line.rstrip().endswith(";"):
            line = "inline " + line[len(m.group(1)):] if m.group(1) else "inline " + line
        out.append(line)
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    src = Path(sys.argv[1]) / "c"
    header = (src / "qrcodegen.h").read_text()
    body = (src / "qrcodegen.c").read_text()

    # The license block at the top of the upstream header, kept verbatim.
    license_end = header.index("*/") + 2
    license_text = header[:license_end]

    commit = "unknown"
    git_head = Path(sys.argv[1]) / ".git" / "HEAD"
    if git_head.exists():
        ref = git_head.read_text().strip()
        if ref.startswith("ref: "):
            ref_file = Path(sys.argv[1]) / ".git" / ref[5:]
            if ref_file.exists():
                commit = ref_file.read_text().strip()
        else:
            commit = ref

    header = strip_guarded(header[license_end:])
    body = strip_guarded(body[body.index("*/") + 2:])

    for old, new in TABLE_PATCH:
        if old not in body:
            print(f"ERROR: upstream no longer contains:\n{old}", file=sys.stderr)
            return 1
        body = body.replace(old, new)

    # `testable` stays `static`: it also prefixes the two constant tables, and
    # an `inline` variable would require C++17.
    body = body.replace("#ifndef QRCODEGEN_TEST\n\t#define testable static  "
                        "// Keep functions private\n#else\n\t#define testable  "
                        "// Expose private functions\n#endif\n",
                        "// `testable` exposes internals to upstream's own test suite; we always\n"
                        "// want the private form. Function definitions below are additionally\n"
                        "// marked inline by this script, which is what a header needs.\n"
                        "#define testable static\n")
    # Left as `static`: an `inline` variable would need C++17, and a per
    # translation unit copy of a string literal pointer costs nothing.

    text = (HEADER.format(commit=commit) + license_text + "\n"
            + inline_functions(header) + "\n" + inline_functions(body) + FOOTER)

    out = Path(__file__).resolve().parent.parent / "src" / "BarcodeKit" / "qrcodegen.h"
    out.write_text(text)
    print(f"wrote {out} ({len(text.splitlines())} lines, upstream {commit[:12]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
