/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef BARCODEKIT_VERSION_H
#define BARCODEKIT_VERSION_H

#define BARCODEKIT_VERSION_MAJOR 0
#define BARCODEKIT_VERSION_MINOR 1
#define BARCODEKIT_VERSION_PATCH 0
#define BARCODEKIT_VERSION_STR "0.1.0"

#endif // BARCODEKIT_VERSION_H
